// Workflow templates for v5 (22 templates across 3 phases)

export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  phase: 1 | 2 | 3;
  icon: string;
  color: string;
  agents: string[];
  estimatedTime: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  usesAi: boolean;
}

export const workflowTemplates: WorkflowTemplate[] = [
  // Phase 1 - Launch (9 templates)
  {
    id: "research-competitors",
    name: "Competitor Research",
    description: "Research competitor AI tools and create comprehensive report",
    category: "Research",
    phase: 1,
    icon: "Search",
    color: "text-blue-400",
    agents: ["Researcher", "Analyst", "Writer"],
    estimatedTime: "3-5 min",
    difficulty: "beginner",
    usesAi: true,
  },
  {
    id: "seo-analysis",
    name: "SEO Analysis",
    description: "Analyze website SEO and suggest improvements",
    category: "Marketing",
    phase: 1,
    icon: "Globe",
    color: "text-green-400",
    agents: ["Crawler", "Analyst", "SEO Expert"],
    estimatedTime: "2-3 min",
    difficulty: "beginner",
    usesAi: true,
  },
  {
    id: "social-calendar",
    name: "Social Media Calendar",
    description: "Generate weekly social media content calendar",
    category: "Content",
    phase: 1,
    icon: "Calendar",
    color: "text-purple-400",
    agents: ["Researcher", "Content Writer", "Planner"],
    estimatedTime: "2-4 min",
    difficulty: "beginner",
    usesAi: true,
  },
  {
    id: "pdf-extract",
    name: "PDF Data Extractor",
    description: "Extract data from PDF and format into spreadsheet",
    category: "Data",
    phase: 1,
    icon: "FileText",
    color: "text-yellow-400",
    agents: ["Parser", "Data Cleaner", "Formatter"],
    estimatedTime: "1-2 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  {
    id: "blog-post",
    name: "Blog Post Writer",
    description: "Write SEO-optimized blog post from topic",
    category: "Content",
    phase: 1,
    icon: "PenTool",
    color: "text-orange-400",
    agents: ["Researcher", "Writer", "SEO Optimizer"],
    estimatedTime: "3-5 min",
    difficulty: "beginner",
    usesAi: true,
  },
  {
    id: "email-summarizer",
    name: "Email Summarizer",
    description: "Summarize long email threads into key points",
    category: "Communication",
    phase: 1,
    icon: "Mail",
    color: "text-red-400",
    agents: ["Parser", "Summarizer"],
    estimatedTime: "1 min",
    difficulty: "beginner",
    usesAi: true,
  },
  {
    id: "meeting-notes",
    name: "Meeting Notes Generator",
    description: "Create meeting notes from transcripts or recordings",
    category: "Productivity",
    phase: 1,
    icon: "Mic",
    color: "text-cyan-400",
    agents: ["Transcriber", "Summarizer", "Action Item Extractor"],
    estimatedTime: "2-3 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  {
    id: "job-application",
    name: "Job Application Helper",
    description: "Customize resume and cover letter for job applications",
    category: "Career",
    phase: 1,
    icon: "Briefcase",
    color: "text-indigo-400",
    agents: ["Parser", "Customizer", "Writer"],
    estimatedTime: "3-4 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  {
    id: "market-research",
    name: "Market Research",
    description: "Research target market and create summary report",
    category: "Research",
    phase: 1,
    icon: "TrendingUp",
    color: "text-pink-400",
    agents: ["Researcher", "Analyst", "Reporter"],
    estimatedTime: "4-6 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  
  // Phase 2 - v1.1 (8 more templates)
  {
    id: "customer-feedback",
    name: "Customer Feedback Analysis",
    description: "Analyze customer reviews and extract insights",
    category: "Analytics",
    phase: 2,
    icon: "MessageSquare",
    color: "text-emerald-400",
    agents: ["Collector", "Analyzer", "Insight Generator"],
    estimatedTime: "2-3 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  {
    id: "invoice-processing",
    name: "Invoice Processing",
    description: "Extract invoice data and create expense report",
    category: "Finance",
    phase: 2,
    icon: "Receipt",
    color: "text-lime-400",
    agents: ["Parser", "Validator", "Reporter"],
    estimatedTime: "1-2 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  {
    id: "product-description",
    name: "Product Description",
    description: "Generate product descriptions for e-commerce",
    category: "E-commerce",
    phase: 2,
    icon: "ShoppingBag",
    color: "text-amber-400",
    agents: ["Researcher", "Writer", "SEO Optimizer"],
    estimatedTime: "2-3 min",
    difficulty: "beginner",
    usesAi: true,
  },
  {
    id: "legal-doc-review",
    name: "Legal Document Review",
    description: "Review contracts and flag potential issues",
    category: "Legal",
    phase: 2,
    icon: "Scale",
    color: "text-slate-400",
    agents: ["Parser", "Legal Expert", "Risk Assessor"],
    estimatedTime: "5-7 min",
    difficulty: "advanced",
    usesAi: true,
  },
  {
    id: "code-review",
    name: "Code Review Assistant",
    description: "Review code and suggest improvements",
    category: "Development",
    phase: 2,
    icon: "Code",
    color: "text-yellow-500",
    agents: ["Parser", "Analyzer", "Recommender"],
    estimatedTime: "2-4 min",
    difficulty: "advanced",
    usesAi: true,
  },
  {
    id: "data-visualization",
    name: "Data Visualization",
    description: "Convert data into charts and infographics",
    category: "Data",
    phase: 2,
    icon: "BarChart",
    color: "text-blue-500",
    agents: ["Analyzer", "Designer", "Exporter"],
    estimatedTime: "3-5 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  {
    id: "translation-workflow",
    name: "Translation Workflow",
    description: "Translate content across multiple languages",
    category: "Localization",
    phase: 2,
    icon: "Globe2",
    color: "text-teal-400",
    agents: ["Translator", "Proofreader", "Cultural Adapter"],
    estimatedTime: "2-4 min",
    difficulty: "beginner",
    usesAi: true,
  },
  {
    id: "presentation-generator",
    name: "Presentation Generator",
    description: "Create presentation slides from topic",
    category: "Productivity",
    phase: 2,
    icon: "Presentation",
    color: "text-violet-400",
    agents: ["Researcher", "Designer", "Slide Writer"],
    estimatedTime: "4-6 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  
  // Phase 3 - v1.2 (5 more templates)
  {
    id: "trend-signal",
    name: "Trend Signal Monitor",
    description: "Monitor market trends and signal opportunities",
    category: "Analytics",
    phase: 3,
    icon: "Activity",
    color: "text-rose-400",
    agents: ["Monitor", "Analyzer", "Signal Generator"],
    estimatedTime: "3-5 min",
    difficulty: "advanced",
    usesAi: true,
  },
  {
    id: "interview-synthesizer",
    name: "Interview Synthesizer",
    description: "Transcribe and synthesize interview audio",
    category: "Research",
    phase: 3,
    icon: "Mic2",
    color: "text-amber-500",
    agents: ["Transcriber", "Summarizer", "Insight Extractor"],
    estimatedTime: "5-8 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  {
    id: "budget-optimizer",
    name: "Budget Optimizer",
    description: "Analyze spending and suggest optimizations",
    category: "Finance",
    phase: 3,
    icon: "DollarSign",
    color: "text-green-500",
    agents: ["Collector", "Analyzer", "Recommender"],
    estimatedTime: "2-4 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  {
    id: "social-sentiment",
    name: "Social Sentiment Analysis",
    description: "Analyze social media sentiment for brand",
    category: "Analytics",
    phase: 3,
    icon: "Heart",
    color: "text-pink-500",
    agents: ["Collector", "Sentiment Analyzer", "Reporter"],
    estimatedTime: "3-5 min",
    difficulty: "intermediate",
    usesAi: true,
  },
  {
    id: "pr-brief-generator",
    name: "PR Brief Generator",
    description: "Create PR briefs from news and updates",
    category: "PR",
    phase: 3,
    icon: "Newspaper",
    color: "text-indigo-500",
    agents: ["Collector", "Analyzer", "Brief Writer"],
    estimatedTime: "2-3 min",
    difficulty: "beginner",
    usesAi: true,
  },
];

// Categories for filtering
export const templateCategories = [
  "All",
  "Research",
  "Marketing",
  "Content",
  "Data",
  "Communication",
  "Productivity",
  "Career",
  "Analytics",
  "Finance",
  "E-commerce",
  "Legal",
  "Development",
  "Localization",
  "PR",
] as const;

export type TemplateCategory = typeof templateCategories[number];
